### ISSUE TITLE
td.scrollspacer causing timetable to be misaligned

### ISSUE THREAD

**Issue by Jaxx7594** [BetterSEQTA/BetterSEQTA-Plus#101]
#main > div > div.container > div > div.header > table > tbody > tr > td.scrollspacer

before deleting the element:
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/101913901/353a7cef-33d8-4b96-92af-574cf5b7fe24)

after deleting the element:
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/101913901/6315b4ef-349f-4807-b69b-40bc04433150)

**Comment by SethBurkart123** [comment]
yes. I've fixed it in a dev build nd it will be fixed later on. I basically just disabled the element (`display: none`).
