### ISSUE TITLE
Building (Again)

### ISSUE THREAD

**Issue by MEGA-Dawg68** [BetterSEQTA/BetterSEQTA-Plus#102]
Hey everybody. I am trying to build this again but once again I have ran into issues
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/140035326/a646d0e9-7e54-4b24-bf7a-7242cd08257b)

Got any tips to fix? I am running Manjaro linux (arch based)

**Comment by Jaxx7594** [comment]
cant remember what exactly I did to fix this, but in package.json it seems I changed "@parcel/transformer-sass": "2.11.0" to "^2.12.0". Try that and tell me if it fixed it ig

**Comment by SethBurkart123** [comment]
> cant remember what exactly I did to fix this, but in package.json it seems I changed "@parcel/transformer-sass": "2.11.0" to "^2.12.0". Try that and tell me if it fixed it ig

That should work. I just applied that change onto the main branch so that if you pull it in the future it will work fine.

**Comment by MEGA-Dawg68** [comment]
It's time to party people. I got it built! And better yet it didn't brick my computer this time :)
