### ISSUE TITLE
Timetable Dates Allignment

### ISSUE THREAD

**Issue by SirCopper8** [BetterSEQTA/BetterSEQTA-Plus#103]
On the timetable, the dates are not aligned in the proper areas and some dates and days are more to the right than the middle. 
For example, Monday is fine but Tuesday is on the left, and Wednesday, Thursday, and Friday are halfway
 through different days and their correct day.

**Comment by Jaxx7594** [comment]
will be fixed in the next release #101

**Comment by SethBurkart123** [comment]
> will be fixed in the next release #101

Thanks!
