### ISSUE TITLE
Custom Theme Creator

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#107]
A new system to create custom themes with css and custom images. In the future some functionality can be turned into tools so that you don't need to know how to code.

**Comment by SethBurkart123** [comment]
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/09343e40-bac8-45d7-97ac-33eb2748eda1)

Progress update

**Comment by SethBurkart123** [comment]
<img width="1440" alt="image" src="https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/e32d0592-1975-47d0-a8b8-e733624e9aa8">
Custom images working... just time to make them save :) 7362dc7

**Comment by SethBurkart123** [comment]
Themes now can save, but cannot be edited. They also send the image on every request (currently being fixed).

**Comment by MEGA-Dawg68** [comment]
"funny" background :)

**Comment by 97-42** [comment]
Should we remove the transparency around any text? I am just looking at the image you posted earlier and the text is quite difficult to read.

**Comment by SethBurkart123** [comment]
Completed!
