### ISSUE TITLE
Notices on Home Page bugged out

### ISSUE THREAD

**Issue by Crazypersonalph** [BetterSEQTA/BetterSEQTA-Plus#110]
They are not loading

![20240508_21h16m01s_grim](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/93847055/33aa9f2d-bd26-4729-bcf7-00b79f56111c)

**Comment by MEGA-Dawg68** [comment]
I think that is just normal SEQTA. I always get that whether I am using BetterSEQTA+ or normal seqta. Did you try without BetterSEQTA+?

**Comment by Crazypersonalph** [comment]
> I think that is just normal SEQTA. I always get that whether I am using BetterSEQTA+ or normal seqta. Did you try without BetterSEQTA+?

Nah its part of the BetterSEQTa home page (not part of normal Seqta)

**Comment by SethBurkart123** [comment]
> > I think that is just normal SEQTA. I always get that whether I am using BetterSEQTA+ or normal seqta. Did you try without BetterSEQTA+?
> 
> Nah its part of the BetterSEQTa home page (not part of normal Seqta)

My school doesn't use notices, but as far as I can tell for me it seems to work. I'd assume it's some issue with the network response changing or something? But I don't know what the network response would look like in an example case. All the request body I get is:
<img width="662" alt="image" src="https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/17448501-d9df-4b8e-abb0-bed61761e5cc">
So one of you guys might have to debug this one...

**Comment by MEGA-Dawg68** [comment]
Mine were working during the week but not anymore...
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/140035326/fda64452-4234-4a93-9bc2-e3c9a2c2ab9a)

**Comment by Crazypersonalph** [comment]
Fixed in b759753

**Comment by Crazypersonalph** [comment]
SEQTA changed the order in which they send preferences
