### ISSUE TITLE
Text on notices in dark mode inconsistent with colouring

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#111]
Hey Seth Burkart,

The text in notices is inconsistant as the text at the bottom is white but everything else is black and unreadable.

Kind Regards,

AR-Cyber

**Comment by SethBurkart123** [comment]
@Crazypersonalph

Do you reckon you could help with this? It'll be probably like 1 line of CSS (I'm hoping)

**Comment by Crazypersonalph** [comment]
Related to #91
