### ISSUE TITLE
Strange Bubbles

### ISSUE THREAD

**Issue by 97-42** [BetterSEQTA/BetterSEQTA-Plus#112]
If you look close enough there are strange bubbles surrounding each letter in dark mode. This was pointed out to me by a classmate.

**Comment by MEGA-Dawg68** [comment]
> If you look close enough there are strange bubbles surrounding each letter in dark mode. This was pointed out to me by a classmate.

Where? I can't find any

**Comment by SethBurkart123** [comment]
Would you be able to take a screenshot so we can have a look, It may be your screens because I don't seem to be able to see it myself.

**Comment by 97-42** [comment]
Never mind, I think it was an issue with his display or resolution
