### ISSUE TITLE
Direct message Spelling

### ISSUE THREAD

**Issue by 97-42** [BetterSEQTA/BetterSEQTA-Plus#114]
I don't know if this is just me but if I make a spelling mistake in a DM it is not picked up by my browser's or system's spell checker. This has become very irritating especially when DMing english teachers

**Comment by Crazypersonalph** [comment]
That is a SEQTA-specific thing, though we can actually change this behaviour with BetterSEQTA.

**Comment by 97-42** [comment]
We could possibly add some spell check and grammar ai modules.

**Comment by MEGA-Dawg68** [comment]
> We could possibly add some spell check and grammar ai modules. I have seen the idea of incorporating AI into better seqta + thrown around in the discussions and I think this is a good use for it that teachers won't get annoyed at.

Not ai, but it should be possible. Spell check isn't an ai

**Comment by SethBurkart123** [comment]
Spellcheck has been enabled from 9ec03ea4d9f21984bc057a32fcd5f65e3e911eda

Expect to see it in the next update!
