### ISSUE TITLE
Firefox settings iframe broken

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#116]
<img width="1440" alt="image" src="https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/87d72e1c-661c-4c1c-af0a-cc812e576126">

As described, I believe it has something to do with permissions. I'm struggling to figure out what's causing this, there are no traces for me in the network tab. The url of the iframe is correct and loads when opened in a new tab but firefox just refuses to load it when on SEQTA.

**Comment by SethBurkart123** [comment]
ummm. actually for some reason it works once submitted to the addons store. But I'm not sure why it isn't working in dev. Still pretty important to fix!

**Comment by MEGA-Dawg68** [comment]
> ummm. actually for some reason it works once submitted to the addons store. But I'm not sure why it isn't working in dev. Still pretty important to fix!

I have the same issues with other extensions when I run as dev. I think it may be a firefox thing

**Comment by SethBurkart123** [comment]
I'll close this for now because it is sorta working. But I've got some ideas for fixing it down the track a bit.

**Comment by ar-cyber** [comment]
Probably put this as not planned instead of closing it as completed.
