### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by 97-42** [BetterSEQTA/BetterSEQTA-Plus#119]
Auto clear a notification once it has been clicked on

**Comment by SethBurkart123** [comment]
> Auto clear a notification once it has been clicked on

Now that's a great idea!

**Comment by 97-42** [comment]
Yeah, I was getting really annoyed whenever I thought i had a new notification but I was one from a few days ago. :)

**Comment by ar-cyber** [comment]
I don't think it's a good idea. It should be able to be toggled in settings, as people will probably want to keep notifications for a long time (I want to get as many as possible).

**Comment by SethBurkart123** [comment]
> I don't think it's a good idea. It should be able to be toggled in settings, as people will probably want to keep notifications for a long time (I want to get as many as possible).

Hahaha, same! I love collecting them for fun, but I do see the logic in having it remove them by default.

**Comment by 97-42** [comment]
> I don't think it's a good idea. It should be able to be toggled in settings, as people will probably want to keep notifications for a long time (I want to get as many as possible).

Sounds fair enough, It can get very annoying though if you expecting results for a test and you see a notification but it is  just a message from two weeks ago.

**Comment by MEGA-Dawg68** [comment]
I have 358, I dont want to loose them lol

**Comment by 97-42** [comment]
> I have 358, I dont want to loose them lol

That's why is should be toggled in the settings (off by default)

**Comment by SethBurkart123** [comment]
> > I have 358, I dont want to loose them lol
> 
> That's why is should be toggled in the settings (off by default)

you reckon off by default? I was thinking on, because the people who collect notifications are rarer to come by...

**Comment by 97-42** [comment]
> > > I have 358, I dont want to loose them lol
> > 
> > That's why is should be toggled in the settings (off by default)
> 
> you reckon off by default? I was thinking on, because the people who collect notifications are rarer to come by...

Probably, I think it's good to have new features initially disable or "off" to allow users to familiarise themselves with it.

**Comment by ar-cyber** [comment]
> > > > I have 358, I dont want to loose them lol
> > > 
> > > 
> > > That's why is should be toggled in the settings (off by default)
> > 
> > 
> > you reckon off by default? I was thinking on, because the people who collect notifications are rarer to come by...
> 
> Probably, I think it's good to have new features initially disable or "off" to allow users to familiarise themselves with it.

Yeah.

**Comment by ar-cyber** [comment]
> I don't think it's a good idea. It should be able to be toggled in settings, as people will probably want to keep notifications for a long time (I want to get as many as possible).

I wiped my collection :(

**Comment by MEGA-Dawg68** [comment]
I think leave it on (Not because I am a rare collector 😀). It is a major selling feature of BetterSEQTA+ in my opinion

**Comment by 97-42** [comment]
Well we want whatever is best for the user. If that means leave it on then so be it.

**Comment by ar-cyber** [comment]
This might actually be where analytics comes in to get how many clears there are in the notification section. Then we can decide.

**Comment by SethBurkart123** [comment]
> This might actually be where analytics comes in to get how many clears there are in the notification section. Then we can decide.

That could be an interesting way of seeing whether people would actually find it useful. Although, we'd have to manually write a custom analytics system to make that possible (although this is very doable within my skillset).

**Comment by 97-42** [comment]
We could change it so it just removes the little notification symbol but the notification stays in the inbox.

**Comment by ar-cyber** [comment]
@97-42 There's a clear button for a reason 👍

**Comment by ar-cyber** [comment]
@SethBurkart123 @Crazypersonalph I feel like this issue is stale and should be closed as not planned.
