### ISSUE TITLE
HTML Text in compose box is weird.

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#120]
Hey Folks that work on this,

The text cursor in the HTML editing area is broken and not up next to the text.

![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/67220260/5533a3f8-5aa0-4e6f-bc60-a58fadfda778)

It's going all over the place.

**Comment by SethBurkart123** [comment]
Ahh yes! Don't worry, in the next update this will actually be fixed. It used to really annoy me as I'd write some of my messages even partially in html.
