### ISSUE TITLE
Notice display on the homepage does not load notices.

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#123]
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/67220260/faa0352a-e863-44e2-9d33-ad0bc247052a)
The notice display at the bottom of the page does not show the notices, just an empty void.

**Comment by ar-cyber** [comment]
The upcoming assessments pane does work; I'm up to date with assignments :)

**Comment by SethBurkart123** [comment]
Should be fixed as of 489fd1b5fdbcb7e5fb7312b23c9da43c37b36277
