### ISSUE TITLE
Timetable capping.

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#127]
The timetable does not allow you to go further than 4:00 PM. 

![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/67220260/8630e1b5-f784-4fe3-8b89-42e9002097f1)

**Comment by ar-cyber** [comment]
If I use the sidebar to access, it does this.

**Comment by MEGA-Dawg68** [comment]
> If I use the sidebar to access, it does this.

Is it just your schools settings?
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/140035326/31ac8485-f572-44c8-add4-98159eec654f)

**Comment by Jaxx7594** [comment]
> > If I use the sidebar to access, it does this.
> 
> Is it just your schools settings? ![image](https://private-user-images.githubusercontent.com/140035326/341306823-31ac8485-f572-44c8-add4-98159eec654f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njk2MDksIm5iZiI6MTcxODg2OTMwOSwicGF0aCI6Ii8xNDAwMzUzMjYvMzQxMzA2ODIzLTMxYWM4NDg1LWY1NzItNDRjOC1hZGQ0LTk4MTU5ZWVjNjU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNzQxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTY3MjU0NTllYzU3Mjg0MzhjMTU5NThhY2U5MGI2ZjFjMDcxZDQwODA0MGQ1MzU1NjI1NDVjY2I0NzYxZjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dBuLsvbClTvpyGYUiLZ89vjBy_o4EaqsNwVNNFjGgc8)

I've just checked all the settings requests that seqta makes, and I couldnt find anything related to a timetable cap. It must be something else, but idk what

**Comment by SethBurkart123** [comment]
Potentially there may be some differences in the version of seqta that your school uses, and so some of the styles may be different causing some kind of conflict. If you do have experience working with devtools and manage to play around and get it working, we might be able to integrate those changes directly into the extension.

**Comment by ar-cyber** [comment]
So it turns out there was a caching problem where the old and new seqta timetable mixed. After a cache clear, it's now fixed.

**Comment by SethBurkart123** [comment]
Yeah so as it turns out this issue is sometimes still present but will be fixed as of v3.4.4
