### ISSUE TITLE
Change default starting page

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#129]
Changes the default page to one of the enabled ones. Still retains the "Home" page.

**Comment by ar-cyber** [comment]
When you load up seqta on from the root (as /), it will load that instead as the Home Category.

**Comment by SethBurkart123** [comment]
Sorry, what I mean't was- how were you "changing" what the "main" page should be? Were you reordering the menu items and placing a different one at the top?

**Comment by ar-cyber** [comment]
Nope. When you go to `https://learn.<insert suffix here>/ or https://student.<insert suffix here>/`, normally it will automatically redirect to #?page=/home. Is there a way to change this? For example, going from the root of the URL `<seqtaurl>/` can go to #?page=/timetable.

**Comment by SethBurkart123** [comment]
currently that isn't an option, how would you propose we introduce it? As in- should we place a different dropdown menu to select the default page?

**Comment by ar-cyber** [comment]
In the settings. Where the change order of icons is, add a dropdown that allows you to select a menu to open by default.

**Comment by SethBurkart123** [comment]
Added as of: dc11997b96e5a36a52a04d88ada8c98312d23d54
