### ISSUE TITLE
Precompiled binaries on Github releases (bulit for us)

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#132]
This would be useful for people who do not have access to a Linux machine AND/OR cannot compile source. This would make it so people can get the changes even if they aren't pushed to Chrome Web Store.

**Comment by SethBurkart123** [comment]
Sure! I'll look at doing that.

**Comment by SethBurkart123** [comment]
For starters, I now have github uploading artifacts for each of the builds: https://github.com/BetterSEQTA/BetterSEQTA-Plus/actions/runs/9589488948 
So every time there is a new push it will make the extension available!

**Comment by ar-cyber** [comment]
Alright.

**Comment by Crazypersonalph** [comment]
They aren't binaries, nor are they pre-compiled (since they aren't binaries) ;)

**Comment by MEGA-Dawg68** [comment]
> They aren't binaries, nor are they pre-compiled (since they aren't binaries) ;)

nerd...
lol

**Comment by ar-cyber** [comment]
> They aren't binaries, nor are they pre-compiled (since they aren't binaries) ;)

Yeah, but you have to compile the source to use the extension. I mean that you should be able to download that compiled one.

**Comment by SethBurkart123** [comment]
Also this is now pretty much good. From now on I'll be releasing each version as a release. This may include betas for experimental features such as the current one! https://github.com/BetterSEQTA/BetterSEQTA-Plus/releases

**Comment by ar-cyber** [comment]
yay
