### ISSUE TITLE
Bring back the about button in settings

### ISSUE THREAD

**Issue by ar-cyber** [BetterSEQTA/BetterSEQTA-Plus#135]

**Comment by SethBurkart123** [comment]
<img width="426" alt="image" src="https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/eff418e4-7f3c-4a29-b641-5d6f46d2ec5a">

The question is... where should we put it, it looks a little weird to have 4 options here!

**Comment by MEGA-Dawg68** [comment]
maybe in the settings tab? as a button?

**Comment by ar-cyber** [comment]
yeah, or like next to the "What's New" button in settings (the megaphone one).

**Comment by ar-cyber** [comment]
> maybe in the settings tab? as a button?

Maybe look at the image from Burkart above your message? It looks weird.

**Comment by Crazypersonalph** [comment]
> maybe in the settings tab? as a button?

We could possibly make an additional info page that has all the version and about stuff, and have that as a button in the settings tab.

**Comment by ar-cyber** [comment]
I think I might close this as not planned as it is stale. You can reopen it but I don't think any activity is going to happen.

**Comment by SethBurkart123** [comment]
I'll just probably put it on the todo list beecause I was thinking it would be nice to have it, I'll re-introduce it with the new svelte settings menu.

**Comment by ar-cyber** [comment]
| add enhancement tag

**Comment by Crazypersonalph** [comment]
Something like d68ba15 ?

**Comment by ar-cyber** [comment]
can you send ss as I cannot compile it right now.

**Comment by ar-cyber** [comment]
wait i got it 
![image](https://github.com/user-attachments/assets/6c5197d4-a9b9-44f8-8fda-64d65d6aabd4)

**Comment by ar-cyber** [comment]
although it should go next to the megaphone in the top right corner
![image](https://github.com/user-attachments/assets/586da567-d3bd-47d5-8d3d-74a7d63e086d)

**Comment by Crazypersonalph** [comment]
> although it should go next to the megaphone in the top right corner ![image](https://private-user-images.githubusercontent.com/67220260/366019375-586da567-d3bd-47d5-8d3d-74a7d63e086d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODIyMTMsIm5iZiI6MTcyNTk4MTkxMywicGF0aCI6Ii82NzIyMDI2MC8zNjYwMTkzNzUtNTg2ZGE1NjctZDNiZC00N2Q1LThkM2QtNzRhN2Q2M2UwODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE1MjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0OGQyNGE1MDNiZGI5NTZhNDIxOGRmNWE5N2M1ODEyYmM5NjkyYWVjNjFiMDdkOGU3OTRkYmU4ZjVhZGE2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjzZ5_7_4onw8awE9yJ3wTCHmefXP_rMHjTHyv3tKyg)

Try f985f94 ?

**Comment by ar-cyber** [comment]
yep. that works except it's not really about but what new instead.
