### ISSUE TITLE
Favicon not found

### ISSUE THREAD

**Issue by OMGerCoder** [BetterSEQTA/BetterSEQTA-Plus#136]
link rel="shortcut icon" href="chrome-extension://afdgaoaclhkhemfkkkonemoapeinchel/data:image..."
The HTML element should be:
link rel="shortcut icon" href="data:image..."

**Comment by SethBurkart123** [comment]
Yeah, I had a look into this and fixed the bug in the dev branch (at the moment at main on github) so that'll be all fixed up next update. You should see it all fixed up after that :)
