### ISSUE TITLE
Firefox version of BetterSEQTA-Plus doesn't exist/is a deadlink

### ISSUE THREAD

**Issue by Crazypersonalph** [BetterSEQTA/BetterSEQTA-Plus#139]
^^^

https://addons.mozilla.org/en-US/firefox/addon/betterseqta-plus/ shows a 404 error.

**Comment by SethBurkart123** [comment]
Just waiting on the firefox team to fix it back up. It was because the description contained "chrome extension" and they didn't like it. So the whole thing got hidden. I just changed it over to "browser extension" so that it can be 're-public-ed'

**Comment by SethBurkart123** [comment]
fixed!
