### ISSUE TITLE
Dark mode dashboard not working

### ISSUE THREAD

**Issue by WizardEels** [BetterSEQTA/BetterSEQTA-Plus#14]
<img width="960" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/148053943/a8317489-f8f8-4366-8041-fd150a381a38">

**Comment by SethBurkart123** [comment]
Great! I'll have a look at it!

**Comment by SethBurkart123** [comment]
It's stale and I'm not able to reproduce this, so I'll close it for now. But if I get any more new revelations then we will fix it up 😭

**Comment by MEGA-Dawg68** [comment]
> It's stale and I'm not able to reproduce this, so I'll close it for now. But if I get any more new revelations then we will fix it up 😭

could it have been colour choices? I know I have made something dark like that but not unreadable

**Comment by SethBurkart123** [comment]
> > It's stale and I'm not able to reproduce this, so I'll close it for now. But if I get any more new revelations then we will fix it up 😭
> 
> could it have been colour choices? I know I have made something dark like that but not unreadable

That text is supposed to be white for dark mode and black for light mode as just a blanket rule. Soooo probably not.

**Comment by ar-cyber** [comment]
yeah this got patched ages ago
