### ISSUE TITLE
No Notices :(

### ISSUE THREAD

**Issue by g00gle-was-my-idea** [BetterSEQTA/BetterSEQTA-Plus#151]
on my home page, the notices don't load. I can see my timetable, my upcoming assessments and my shortcuts, but no notices. I have to actaully go to the notices page if I want to view them.

**Comment by MEGA-Dawg68** [comment]
![image](https://github.com/user-attachments/assets/be4acc1f-e3d3-4c7b-a164-b95813de984b)
I can confirm

**Comment by SethBurkart123** [comment]
What version you on? It shows up in the bottom right corner when the page is loading.

**Comment by g00gle-was-my-idea** [comment]
<img width="1428" alt="Screenshot 2024-08-28 at 8 38 29 pm" src="https://github.com/user-attachments/assets/8636470c-991d-4e96-aab8-f527c624c2bf">
3.3.1 I think

**Comment by SethBurkart123** [comment]
did they previously work?

**Comment by ar-cyber** [comment]
Alright. This is an issue with the Chrome web store version of BetterSEQTA. Using the instructions on the "readme.md" file, download the zip file on the releases page and sideload it.

**Comment by ar-cyber** [comment]
> ![image](https://private-user-images.githubusercontent.com/140035326/362257224-be4acc1f-e3d3-4c7b-a164-b95813de984b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODA2NTIsIm5iZiI6MTcyNDg4MDM1MiwicGF0aCI6Ii8xNDAwMzUzMjYvMzYyMjU3MjI0LWJlNGFjYzFmLWUzZDMtNGM3Yi1hMTY0LWI5NTgxM2RlOTg0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMTI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWEzYmRiZTg4MzEzNjNhOWFjOGY3Nzg3NWI3NzI4ZTA0YmYzNzFiOGE4YzY2YzhhYThlN2UzODcyY2NlODM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JDO5smGpaUp6IM_HJl2RZjlnbFB0m-oJVJWhXEmp9zg) I can confirm

BE CAREFUL WITH WHAT YOU SEND. THAT CONTAINS PERSONAL INFORMATION AND SHOULD BE DELETED ACCORDINGLY.

**Comment by g00gle-was-my-idea** [comment]
> did they previously work? (as in just before this update?)

no, but I also don't know when or how many times it's updated

**Comment by ar-cyber** [comment]
> > did they previously work? (as in just before this update?)
> 
> no, but I also don't know when or how many times it's updated
What browser do you use?

**Comment by ar-cyber** [comment]
![image](https://github.com/user-attachments/assets/431a5c69-535f-451a-a721-d90db78e26ab)
Works fine for me

**Comment by g00gle-was-my-idea** [comment]
> > > did they previously work? (as in just before this update?)
> > 
> > 
> > no, but I also don't know when or how many times it's updated
> 
> What browser do you use?

Opera GX

**Comment by g00gle-was-my-idea** [comment]
> > > > did they previously work? (as in just before this update?)
> > > 
> > > 
> > > no, but I also don't know when or how many times it's updated
> > 
> > 
> > What browser do you use?
> 
> Opera GX

But I also opened BetterSEQTA Plus in Google Chrome and it didn't work either.

**Comment by ar-cyber** [comment]
> > > > > did they previously work? (as in just before this update?)
> > > > 
> > > > 
> > > > no, but I also don't know when or how many times it's updated
> > > 
> > > 
> > > What browser do you use?
> > 
> > 
> > Opera GX
> 
> But I also opened BetterSEQTA Plus in Google Chrome and it didn't work either.

Sideload the extension: download the zip in latest release, go to chrome://extensions, extract zip, click load unpacked, click folder.

**Comment by g00gle-was-my-idea** [comment]
> > > > > > did they previously work? (as in just before this update?)
> > > > > 
> > > > > 
> > > > > no, but I also don't know when or how many times it's updated
> > > > 
> > > > 
> > > > What browser do you use?
> > > 
> > > 
> > > Opera GX
> > 
> > 
> > But I also opened BetterSEQTA Plus in Google Chrome and it didn't work either.
> 
> Sideload the extension: download the zip in latest release, go to chrome://extensions, extract zip, click load unpacked, click folder.

do you think you could simplify the steps a bit more? I'm a bit confused. I think I've downloaded the zip and unpacked it, but I don't know what to do from there. It also says it's a different version to the original extension I got (zip is 3.3.0, o.g. is 3.3.1)
<img width="1430" alt="Screenshot 2024-08-29 at 9 23 21 pm" src="https://github.com/user-attachments/assets/8048bd32-8da3-4c4c-8940-da29255d3c4f">

**Comment by ar-cyber** [comment]
remove the original extension and click "Load Unpacked" in the menu, selecting the folder in the file selection screen.

**Comment by Crazypersonalph** [comment]
I fixed this a while back but it seems like it may have reared its head again.

**Comment by g00gle-was-my-idea** [comment]
> remove the original extension and click "Load Unpacked" in the menu, selecting the folder in the file selection screen.

<img width="507" alt="Screenshot 2024-08-30 at 9 51 55 pm" src="https://github.com/user-attachments/assets/e0dd117c-6719-4979-bf41-65ef7b86b636">

**Comment by MEGA-Dawg68** [comment]
> > remove the original extension and click "Load Unpacked" in the menu, selecting the folder in the file selection screen.
> 
> <img alt="Screenshot 2024-08-30 at 9 51 55 pm" width="507" src="https://private-user-images.githubusercontent.com/179697520/363198330-e0dd117c-6719-4979-bf41-65ef7b86b636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjY5ODEsIm5iZiI6MTcyNTE2NjY4MSwicGF0aCI6Ii8xNzk2OTc1MjAvMzYzMTk4MzMwLWUwZGQxMTdjLTY3MTktNDk3OS1iZjQxLTY1ZWY3Yjg2YjYzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNDU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWQ4N2JmNjExYjc3MDJhMTc3YTg1ZDdlZDgxM2Q3NzkwZDc4NWZjYmMwYTE0NTYzODQ3Y2JhMjMzN2EzYTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HEDKW0OmSC_KAIRwfX35LwbYOlKA9iUzNcCcKyKAZ30">

You are trying to open your downloads, point it to better seqta instead of download

**Comment by ar-cyber** [comment]
@SethBurkart123 Can you close this as "Completed" as it seems it's fixed.
