### ISSUE TITLE
Firefox CSS Inconsistencies

### ISSUE THREAD

**Issue by Crazypersonalph** [BetterSEQTA/BetterSEQTA-Plus#164]
Issue to track fixing various CSS and JS inconsistencies within firefox.

**Comment by ar-cyber** [comment]
Can you elaborate here? Like do you mean that certain styling is broken or something else.

**Comment by Crazypersonalph** [comment]
In Notices, Courses pages, and Assessment pages, iFrame CSS is not applied consistently or even at all.

![image](https://github.com/user-attachments/assets/f7ca0f04-b881-413e-a9ab-20afd466519a)

**Comment by ar-cyber** [comment]
so basically what happened before when chrome has this issue, but it's on the Firefox branch?

**Comment by Crazypersonalph** [comment]
Notices fixed in d1466da

**Comment by Crazypersonalph** [comment]
Can also confirm fixed assessments and courses, and no problems with Chrome.

**Comment by ar-cyber** [comment]
very quick
