### ISSUE TITLE
[BUG] When loading up other websites with low html content errors appear in the console.

### ISSUE THREAD

**Issue by SllverSpace** [BetterSEQTA/BetterSEQTA-Plus#175]
**Describe the bug**
The error does not cause anything visible or anything significant, it's just an error saying that it cannot find an element.
TypeError: Cannot read properties of undefined (reading 'textContent')
    at SEQTA.ts-6x27o2-z.js:265:53945
It might be a good idea to check the url loaded inside the browser somehow or put in error cases to avoid it logging to the console.

**To Reproduce**
Just load up a website, this error will only happen when the page has no elements or near no elements, examples being js canvas focused websites, an example is https://silverspace.online (sorry for plug, just a easy option). You'll get this error:
TypeError: Cannot read properties of undefined (reading 'textContent')
    at SEQTA.ts-6x27o2-z.js:265:53945

**Expected behaviuor**
It should either has a check for being on the correct url in some way, or it should handle the error instead of logging something to the console.

**Screenshots**
not needed

**Desktop (please complete the following information):**
load up a website without much html content, and then inspect the page and go the console, the error should be there.

**Additional context**
I find this annoying because it always makes me think I have an error in my code whenever developing websites.

**Comment by SethBurkart123** [comment]
Thanks so much! I've fixed it in 84eaecd. So in the next version you will see this totally fixed.
