### ISSUE TITLE
[BUG] broken

### ISSUE THREAD

**Issue by blackxfiied** [BetterSEQTA/BetterSEQTA-Plus#178]
**Describe the bug**
betterseqta not wwork!!

**To Reproduce**
try betterseqta

**Expected behaviuor**
betterseqta work

**Screenshots**
<img width="1580" alt="Screenshot 2024-10-14 at 09 09 42" src="https://github.com/user-attachments/assets/aa2bb9a0-111e-4e1e-9786-5609b19caa63">

**Desktop (please complete the following information):**
 - OS: macOS 15.1 Beta (24B5035e)
 - ~~If using Windows, the build number. Find this by using ```winver``` and copying down the build id.~~

**Additional context**
problem happened sometime during holidays
betterseqta obviouslt used t work but now it not working 💀

**Comment by SethBurkart123** [comment]
Are you able to open up the console and send over what it logs?

**Comment by blackxfiied** [comment]
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/a2c34607-3aaf-4ccf-908f-b2e51886ac66">
holy moly!!!!

**Comment by ar-cyber** [comment]
That's a bug. It's having trouble loading the script! @SethBurkart123 should be able to look into this.

**Comment by ar-cyber** [comment]
Might've clashed with holiday updates.

**Comment by SethBurkart123** [comment]
Where is it installed from? Is it from the Chrome web store version or a custom build?

**Comment by blackxfiied** [comment]
webstore -- no idea if it's dev but straight off of the webstore so likely not

**Comment by SethBurkart123** [comment]
> webstore -- no idea if it's dev but straight off of the webstore so likely not

hmmm. I haven't changed it since: Aug 28, 2024...
Which means that was just the hotfix and it's been working for everybody else.. including me, also on the 15.1 beta using arc... have you tried reinstalling it?

**Comment by ar-cyber** [comment]
@SethBurkart123 Has made a patch to the Chrome Web Store branch of BetterSEQTA+. Can you reinstall the extension?

**Comment by ar-cyber** [comment]
> webstore -- no idea if it's dev but straight off of the webstore so likely not

It's not dev.

**Comment by blackxfiied** [comment]
I'm so confused rn, upon checking my extension, I was on 2.0.8, and was getting the manifest v2 offloading warning
upon reinstallation it's still happening -- my arc installation might be cooked

**Comment by zhangruoshu** [comment]
I have similar issues that Better SEQTA+ is not working.  Refuse to load the script.  Tried last night and this morning.  Still not working.
My chrome is Version 130.0.6723.59.  Better Seqta+ Version 3.3.1
Better Seqta+ is working on my other computer with Chrome Version 129.
![image](https://github.com/user-attachments/assets/f53c1fa7-0103-42d7-b6db-47c6a7578c19)

**Comment by SethBurkart123** [comment]
> @SethBurkart123 Please kindly help. I have similar issues that Better SEQTA+ is not working. Refuse to load the script. Tried last night and just now. Still not working. I will try again in a few hours. My chrome is Version 130.0.6723.59. Better Seqta+ Version 3.3.1 Better Seqta+ is working on my other computer with Chrome Version 129. ![image](https://private-user-images.githubusercontent.com/185436776/377658102-f53c1fa7-0103-42d7-b6db-47c6a7578c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDkxNzgsIm5iZiI6MTcyOTIwODg3OCwicGF0aCI6Ii8xODU0MzY3NzYvMzc3NjU4MTAyLWY1M2MxZmE3LTAxMDMtNDJkNy1iNmRiLTQ3YzZhNzU3OGMxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QyMzQ3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2QwNTQxYWI3OGU5NjZiZWQxOGIyZjczNTMxNjNhNWIyMDk0MDhmOGQ0ZjdlOGM1YmUwYTEyNDcwMWViMzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5tYE9IO3qKltYP-VdAlu0yuZ1CNO9KBQUUweJBfkPI0)

This is a known issue with Chrome 130 that's fixed in version `3.3.2`.  It's currently pending review on the store, once that releases it will be working.

**Comment by Crazypersonalph** [comment]
Fixed once hotfix is approved.

**Comment by Crazypersonalph** [comment]
@SethBurkart123 Is there a commit for the hotfix?

**Comment by SethBurkart123** [comment]
> @SethBurkart123 Is there a commit for the hotfix?

Not at the moment, I'm quite busy at the moment so it was just a throw together. If you look at the `Chrome Extension Tools` (CRXjs) github repo there is a long issue with heaps of fixes for the problem including some permanent patches. So potentially if you wanted to fix that up you could take a look, but I'm just busy for at least a few days.
