### ISSUE TITLE
[BUG] Better Seqta doesnt load with the latest chrome update

### ISSUE THREAD

**Issue by MrNO13** [BetterSEQTA/BetterSEQTA-Plus#179]
Computer: Macbook Air M1, Sonoma 14.4
Chrome version: Version 130.0.6723.59
Computer Controlled by JAMF | Connect 2.37.0, controlling app updates and downloads through "Self Service", controls app setting (Not able to open Dev console for debugging)

Bug;
Better Seqta will not load on the latest chrome update, was able to recreate by updating chrome on another device. Screen shows the settings box when extension is clicked but only default seqta. Computer has been reset and problem persists.

**Comment by MrNO13** [comment]
Edit, Better seqta appears to try to load on each navigation change (ie open a course). Page turns greyscale and then reverts to default colour scheme

**Comment by ar-cyber** [comment]
There is a current bug regarding BetterSEQTA on Macs where the code does not load correctly, which was an issue with Safari and older versions of Chrome. The latest version of Chrome seems to work ok though:
![image](https://github.com/user-attachments/assets/0f08f5e5-12d8-4b27-8908-b3f904d09971)

**Comment by MrNO13** [comment]
I'll try to recreate the issue on a non-school computer, it may be something with school settings. Chrome had an update yesterday are you using the newest update?

**Comment by SethBurkart123** [comment]
I figured it out. This is an issue with the new chrome 130 update breaking the library we are using [crxjs](https://github.com/crxjs/chrome-extension-tools/issues/918). I'll push an update that fixes it!

**Comment by MrNO13** [comment]
Cool, thanks heaps

**Comment by SethBurkart123** [comment]
It's uploaded to the store, so hopefully the update will be live in a couple of hours.
