### ISSUE TITLE
Animation for DM loading

### ISSUE THREAD

**Issue by MEGA-Dawg68** [BetterSEQTA/BetterSEQTA-Plus#39]
could we change the default loading animation for when you search DMs to a EvenBetterSEQTA, it doesn't look very consistent (except for the colours of it)

**Comment by SethBurkart123** [comment]
Good point. Not quite sure how to edit it, but I'll have a look at it at some point.

**Comment by MEGA-Dawg68** [comment]
No rush, probably just me that noticed it. I was compiling my project and everything slowed down and I saw it :)

**Comment by ar-cyber** [comment]
> Needs enhancement tag

**Comment by ar-cyber** [comment]
Yep, this exists now.
