### ISSUE TITLE
No settings panel when built from source

### ISSUE THREAD

**Issue by MEGA-Dawg68** [BetterSEQTA/BetterSEQTA-Plus#56]
Well, there could be I don't know, but I was building EvenBetterSEQTA from source using the instructions given and I get this:
![image](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/9bfbd605-e42f-440d-ae78-d7e64f8070ae)

I built it on Windows, I do have a linux dual boot there if I need to use that to build it

**Comment by Crazypersonalph** [comment]
Have you looked at #50?

**Comment by MEGA-Dawg68** [comment]
No I didn't, I redid the entire thing and still the same outcome

**Comment by Crazypersonalph** [comment]
Could you please post your console output upon opening and your environment details?

**Comment by SethBurkart123** [comment]
> I would but I deleted the built version and tried to recompile following the new instructions but the scripts don't work, no build folder is created Edit: I will try and compile on Pop!_OS, maybe it is a Windows thing

oo, well thats sad. I'll make sure to update that documentation and say that currently the script isn't working :O

**Comment by Crazypersonalph** [comment]
I've been compiling on both my windows and Linux dual boots, have you kept your version of node/npm up to date?

Also have you kept the packages as the same version as the package lock? 'npm ci'

Try using pnpm to build to see if that works

**Comment by Crazypersonalph** [comment]
Any updates?

**Comment by MEGA-Dawg68** [comment]
Kinda can't build it anymore #67 my linux distro got bricked (I managed to fix it) but I can't use npm anymore as it says it is installed but it isn't (????)

Windows script just crashes immediately

Long story short: No

**Comment by SethBurkart123** [comment]
> Kinda can't build it anymore #67 my linux distro got bricked (I managed to fix it) but I can't use npm anymore as it says it is installed but it isn't (????)
> 
> Windows script just crashes immediately
> 
> Long story short: No

I'll have to drop in and help you maybe in a call in discord. We'll be able to figure it out.

**Comment by MEGA-Dawg68** [comment]
alright, pm me anytime

**Comment by Crazypersonalph** [comment]
> Kinda can't build it anymore #67 my linux distro got bricked (I managed to fix it) but I can't use npm anymore as it says it is installed but it isn't (????)
> 
> Windows script just crashes immediately
> 
> Long story short: No

I have almost bricked my UEFI like 6 times, and my linux partition countless times lmao.

**Comment by Crazypersonalph** [comment]
> Kinda can't build it anymore #67 my linux distro got bricked (I managed to fix it) but I can't use npm anymore as it says it is installed but it isn't (????)
> 
> Windows script just crashes immediately
> 
> Long story short: No

Which distro? Chat on Discord, I can help out
It might be registered as installed on your package manager but the files managed to get corrupted somehow.

Anyways, this isn't a channel for tech support, we can talk on Discord though.

**Comment by SethBurkart123** [comment]
Hey @MEGA-Dawg68,

I've just overhauled the whole compilation process of the project, so we are now using parcel so that everything packages a lot faster. Which means finally I don't have two separate packages. Just take a look at the updated readme on instructions and see whether that works for you. 

:)

**Comment by SethBurkart123** [comment]
I'll close this as it's pretty stale, but everything should be a lot easier for oyu now @MEGA-Dawg68

**Comment by MEGA-Dawg68** [comment]
> I'll close this as it's pretty stale, but everything should be a lot easier for oyu now @MEGA-Dawg68

I will test it out, in a VM this time :)
