### ISSUE TITLE
Switching to Svelte for Enhanced Performance on Slow Devices

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#64]
I'm exploring the idea of switching from React to Svelte for our embedded components and pages, especially given our application's usage on slower laptops. I'd love to hear your thoughts on this. Here's a quick breakdown of why Svelte might be a better fit:

- **Performance Boost:** Svelte compiles to highly efficient vanilla JS, offering faster load times and smoother performance – a key advantage for users on slower laptops.

- **Simpler Code:** With its less verbose syntax, Svelte can make our codebase more readable and easier to maintain.

- **Reduced Bundle Size:** Svelte's leaner output means smaller bundles, leading to _slightly_ quicker page loads, a crucial factor for our target user base.

- **No Virtual DOM:** This reduces memory consumption, enhancing performance on older, less powerful laptops.

Looking forward to your feedback and suggestions!

And because its always running in the background in SEQTA it may give some pretty major gains!

**Comment by SethBurkart123** [comment]
This is now in the works! I've managed to get full tab switching converted from the old logic in react :)

**Comment by SethBurkart123** [comment]
I'll probably close this for now, because it really isn't fully feasible to recreate it without a LOT of time on our hands. I've moved the project to vite and am using https://million.dev/ to try and squeeze a bit more performance out.

**Comment by ar-cyber** [comment]
No github, this is not done.

**Comment by SethBurkart123** [comment]
Moved back on as dev on this is going ahead under the [`svelte`](https://github.com/BetterSEQTA/BetterSEQTA-Plus/tree/svelte) branch

**Comment by ar-cyber** [comment]
This one's going to be good. I can make BetterSEQTA run on my Pentium!

**Comment by MEGA-Dawg68** [comment]
> This one's going to be good. I can make BetterSEQTA run on my Pentium!

I had a surface go 2. The animated background would lag at times :(

**Comment by ar-cyber** [comment]
Will this only apply to the settings page or the entire extension?

**Comment by SethBurkart123** [comment]
> Will this only apply to the settings page or the entire extension?

I'm completely moving away from react (in all other custom pages as well) except for a couple of components that need to stay at the present moment like the colour picker (as I'm not quite willing to make it from scratch right now).

**Comment by ar-cyber** [comment]
So it's just going into a couple little steps, right.

**Comment by 97-42** [comment]
> > This one's going to be good. I can make BetterSEQTA run on my Pentium!
> 
> I had a surface go 2. The animated background would lag at times :(

I don't think it is the laptop but more the screen, they are only 60Hz and most of the time cant use all of it.

**Comment by MEGA-Dawg68** [comment]
> > > This one's going to be good. I can make BetterSEQTA run on my Pentium!
> > 
> > 
> > I had a surface go 2. The animated background would lag at times :(
> 
> I don't think it is the laptop but more the screen, they are only 60Hz and most of the time cant use all of it.



> > > This one's going to be good. I can make BetterSEQTA run on my Pentium!
> > 
> > 
> > I had a surface go 2. The animated background would lag at times :(
> 
> I don't think it is the laptop but more the screen, they are only 60Hz and most of the time cant use all of it.

It isn't the 60Hz screen. The 60Hz won't cause issues. It was the CPU that couldn't handle anything. Completely a hardware issue
