### ISSUE TITLE
Grade Calculator?

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#8]

**Comment by 97-42** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>SEQTA Grade Calculator</title>
    <script>
        function calculateGrade() {
            var assessmentElements = document.querySelectorAll('.assessment');
            var totalScore = 0;

            // Loop through each assessment to calculate the total score
            assessmentElements.forEach(function(assessmentElement) {
                var value = parseFloat(assessmentElement.value);
                if (!isNaN(value)) {
                    totalScore += value;
                }
            });

            var grade = '';

            // Determine the grade based on the total score
            if (totalScore >= 85) {
                grade = 'A';
            } else if (totalScore >= 70) {
                grade = 'B';
            } else if (totalScore >= 55) {
                grade = 'C';
            } else if (totalScore >= 40) {
                grade = 'D';
            } else {
                grade = 'F';
            }

            // Display the result
            document.getElementById('result').innerHTML = "Total Score: " + totalScore + " | Grade: " + grade;
        }

        // Automatically calculate the grade when any assessment input value changes
        var assessmentElements = document.querySelectorAll('.assessment');
        assessmentElements.forEach(function(assessmentElement) {
            assessmentElement.addEventListener('input', calculateGrade);
        });
    </script>
</head>
<body>
    <h1>SEQTA Grade Calculator</h1>
    <form>
        <label for="assignment1">Assignment 1 Score:</label>
        <input type="text" class="assessment" id="assignment1"><br>

        <label for="assignment2">Assignment 2 Score:</label>
        <input type="text" class="assessment" id="assignment2"><br>

        <label for="exam">Exam Score:</label>
        <input type="text" class="assessment" id="exam"><br>
    </form>
    <p id="result"></p>
</body>
</html>

**Comment by 97-42** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>SEQTA Grade Calculator</title>
    <script>
        function calculateGrade() {
            var assessmentElements = document.querySelectorAll('.assessment');
            var totalScore = 0;

            // Loop through each assessment to calculate the total score
            assessmentElements.forEach(function(assessmentElement) {
                var value = parseFloat(assessmentElement.value);
                if (!isNaN(value)) {
                    totalScore += value;
                }
            });

            var grade = '';

            // Determine the grade based on the total score
            if (totalScore >= 85) {
                grade = 'A';
            } else if (totalScore >= 70) {
                grade = 'B';
            } else if (totalScore >= 55) {
                grade = 'C';
            } else if (totalScore >= 40) {
                grade = 'D';
            } else {
                grade = 'F';
            }

            // Display the result
            document.getElementById('result').innerHTML = "Total Score: " + totalScore + " | Grade: " + grade;
        }

        // Automatically calculate the grade when any assessment input value changes
        var assessmentElements = document.querySelectorAll('.assessment');
        assessmentElements.forEach(function(assessmentElement) {
            assessmentElement.addEventListener('input', calculateGrade);
        });
    </script>
</head>
<body>
    <h1>SEQTA Grade Calculator</h1>
    <form>
        <label for="assignment1">Assignment 1 Score:</label>
        <input type="text" class="assessment" id="assignment1"><br>

        <label for="assignment2">Assignment 2 Score:</label>
        <input type="text" class="assessment" id="assignment2"><br>

        <label for="exam">Exam Score:</label>
        <input type="text" class="assessment" id="exam"><br>
    </form>
    <p id="result"></p>
</body>
</html>

**Comment by 97-42** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>Grade Calculator</title>
</head>
<body>
    <h1>Grade Calculator</h1>
    <form>
        <label for="assignment1">Assignment 1 Score:</label>
        <input type="number" id="assignment1" class="assessment"><br>

        <label for="assignment2">Assignment 2 Score:</label>
        <input type="number" id="assignment2" class="assessment"><br>

        <label for="exam">Exam Score:</label>
        <input type="number" id="exam" class="assessment"><br>

        <label for="totalScore">Total Score:</label>
        <input type="text" id="totalScore" disabled><br>

        <label for="grade">Grade:</label>
        <input type="text" id="grade" disabled><br>
    </form>

    <script>
        function calculateGrade() {
            const assessmentElements = document.querySelectorAll('.assessment');
            let totalScore = 0;

            assessmentElements.forEach(function(assessmentElement) {
                const value = parseFloat(assessmentElement.value);
                if (!isNaN(value)) {
                    totalScore += value;
                }
            });

            const grade = calculateLetterGrade(totalScore);

            document.getElementById('totalScore').value = totalScore;
            document.getElementById('grade').value = grade;
        }

        function calculateLetterGrade(score) {
            if (score >= 85) {
                return 'A';
            } else if (score >= 70) {
                return 'B';
            } else if (score >= 55) {
                return 'C';
            } else if (score >= 40) {
                return 'D';
            } else {
                return 'F';
            }
        }

        // Automatically calculate the grade when any assessment input value changes
        const assessmentElements = document.querySelectorAll('.assessment');
        assessmentElements.forEach(function(assessmentElement) {
            assessmentElement.addEventListener('input', calculateGrade);
        });

        calculateGrade(); // Calculate the grade on page load
    </script>
</body>
</html>
[GradeCalcutaltor.txt](https://github.com/SethBurkart123/EvenBetterSEQTA/files/12911280/GradeCalcutaltor.txt)

**Comment by SethBurkart123** [comment]
Nice! That is a great script. One thing that I was thinking though, maybe a future idea. But some schools group assignments, exams etc. into separate groups where eg.
1. Average of exams = 40% of grade
2. Average of assignments = 60% of grade
Maybe we could push this even further to make it allow you to group your different assignments as like a advanced option or something! But this is a great start, once I have finished up with the background images and videos I'll drop this into the code.

**Comment by MEGA-Dawg68** [comment]
For assessments, SEQTA doesn't know how much the assessment is weighted, the student will need to input that.

**Comment by SethBurkart123** [comment]
Yeah, definitely.

**Comment by 97-42** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>Grade Calculator</title>
</head>
<body>
    <form>
        <label for="assignment2">Assignment 2 Score:</label>
        <input type="number" id="assignment2" class="assessment"><br>

        <label for="exam">Exam Score:</label>
        <input type="number" id="exam" class="assessment"><br>

        <label for="assessmentPercentage">Assessment Percentage (%):</label>
        <input type="number" id="assessmentPercentage"><br>

        <label for="totalScore">Total Score:</label>
        <input type="text" id="totalScore" disabled><br>

        <label for="grade">Grade:</label>
        <input type="text" id="grade" disabled><br>
    </form>

    <script>
        function calculateGrade() {
            const assessmentElements = document.querySelectorAll('.assessment');
            const assessmentPercentage = parseFloat(document.getElementById('assessmentPercentage').value) || 0;
            let totalScore = 0;

            assessmentElements.forEach(function (assessmentElement) {
                const value = parseFloat(assessmentElement.value);
                if (!isNaN(value)) {
                    totalScore += value;
                }
            });

            totalScore *= assessmentPercentage / 100;

            const grade = calculateLetterGrade(totalScore);

            document.getElementById('totalScore').value = totalScore;
            document.getElementById('grade').value = grade;
        }

        function calculateLetterGrade(score) {
            if (score >= 85) {
                return 'A';
            } else if (score >= 70) {
                return 'B';
            } else if (score >= 55) {
                return 'C';
            } else if (score >= 40) {
                return 'D';
            } else {
                return 'F';
            }
        }

        const assessmentElements = document.querySelectorAll('.assessment');
        assessmentElements.forEach(function (assessmentElement) {
            assessmentElement.addEventListener('input', calculateGrade);
        });

        calculateGrade();
    </script>
</body>
</html>

**Comment by willtea** [comment]
> For assessments, SEQTA doesn't know how much the assessment is weighted, the student will need to input that.

Hi, this might be a bit random but I think SEQTA might, well with my school it does. to find the weighting of an assessment follow:

1. Assessments tab
2. Select the desired assessment
3. Click on three dots at the top right of the page (should be next to the assessment date)
4. Print cover sheet
5. access document and assessment weight should be in there.

I don't know if this is what you meant but might be useful nonetheless. Thanks for all of your work on making such an outdated software modern and cool.

**Comment by SethBurkart123** [comment]
> > For assessments, SEQTA doesn't know how much the assessment is weighted, the student will need to input that.
> 
> Hi, this might be a bit random but I think SEQTA might, well with my school it does. to find the weighting of an assessment follow:
> 
> 1. Assessments tab
> 2. Select the desired assessment
> 3. Click on three dots at the top right of the page (should be next to the assessment date)
> 4. Print cover sheet
> 5. access document and assessment weight should be in there.
> 
> I don't know if this is what you meant but might be useful nonetheless. Thanks for all of your work on making such an outdated software modern and cool.

That looks pretty cool (and super useful), because that would mean that it would be much more accurate by default. I tried it, But with my school it basically just errors out for some reason 😭.

**Comment by MEGA-Dawg68** [comment]
I thought this would tell you the grade you are sitting on? If so, you could always just have the user enter the weight of the assessment. If not, then idk what this issue is about lol

**Comment by 97-42** [comment]
What is our progress looking like on this?

**Comment by ar-cyber** [comment]
What's the progress on this one?

**Comment by SethBurkart123** [comment]
Currently low priority. If somebody else would like to go and write up an implementation and add it to the UI with a setting feel free though.

**Comment by Crazypersonalph** [comment]
It looks like not much has been done/is going to be done about this so I'll close this for the time being

**Comment by ar-cyber** [comment]
GitHub, it's NOT done again. 

Someone move it to not planned please.

**Comment by SethBurkart123** [comment]
Ladies and gentlemen. I present to you...

<img width="361" alt="image" src="https://github.com/user-attachments/assets/e9573de9-5d73-41b8-81e7-dbf9947239e9">

**Comment by ar-cyber** [comment]
WOOOO

**Comment by ar-cyber** [comment]
Although letter grades dont work...

**Comment by 97-42** [comment]
she'll be right

**Comment by ar-cyber** [comment]
> she'll be right
huh
