### ISSUE TITLE
Adding shortcut for website

### ISSUE THREAD

**Issue by TYP3D** [BetterSEQTA/BetterSEQTA-Plus#86]
when trying to add a shortcut, like "https://duolingo.com/learn" as "Duolingo" it fails to set as a shortcut on the home page

Hope this is fixable, thanks!

**Comment by SethBurkart123** [comment]
Thanks for that @TYP3D!

I'll have that fixed in the next release for you!

**Comment by SethBurkart123** [comment]
300c98b

**Comment by TYP3D** [comment]
Awesome job seth, glad you could fix that, Ill be sure to report any new bugs!
