### ISSUE TITLE
Bug: The user denied permission to access the database.

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#89]
When cross site cookies are blocked backgrounds do not work (as they use indexed DB). It returns this error:
```
Uncaught (in promise) DOMException: The user denied permission to access the database.
```
The fix will be just to inform the user that they need to enable cross site cookies. Common places they will be blocked from:

- Brave browser default shields
- Ad blockers
- chrome://settings/content under the third-party cookies section.

**Comment by MEGA-Dawg68** [comment]
I don't use brave because of this bug,

**Comment by SethBurkart123** [comment]
> I don't use brave because of this bug,

All you have to do is disable brave shields setting that breaks it. Either disable brave shields on seqta completely or change it to allow all cookies.

<img width="1439" alt="image" src="https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/06a7f4d5-289b-485f-9f2f-13006e9e8c9e">

**Comment by MEGA-Dawg68** [comment]
That never worked for me, Either the IT department was sabotaging every other web browser but Edge again or My Brave settings had overriden my shields choice. Doesn't matter anyway, I don't like the way Brave is heading so I won't use it.

**Comment by SethBurkart123** [comment]
Fair, the problem is that a simple setting or ad blocker will totally break the feature. It's not reasonable to use the localstorage for file storage as that will make the files ~30% larger. So i'd like to stay using indexedDB. But we just need to display something to the user. I'm not quite sure what though.

**Comment by Crazypersonalph** [comment]
I've never had this problem, how do I replicate it?

**Comment by Crazypersonalph** [comment]
I have an idea: What about instead of storing the IndexedDB bucket in a way that belongs to the extension, we store the bucket in a way so that it belongs to the actual Seqta site; we use something like background.js or seqta.js to store the bucket, and make it communicate with the popup so that it works.

**Comment by Crazypersonalph** [comment]
See the current IndexedDB's bucket's origin belongs to the extension, what if we use the background.js script/service workers in handle retrieving and dumping into the bucket, instead of the popup.

**Comment by MEGA-Dawg68** [comment]
@SethBurkart123 @Crazypersonalph 
I had spent 1 hour setting flags and settings so It was the most optimal browser for me, it could just be I set the wrong flag or setting. I don't think we should go change things like that when we could be moving BetterSEQTA+ along with new features. Most people just just chrome or edge (yuck). They aren't going to experience the issue I'm having. For the 2 people who are probably using Brave and BetterSEQTA+, we could make a wiki or documentation on the way to fix the issue. We would need the documentation for any big features that get implemented like custom theming and a theme store.
Sorry for the essay :)

**Comment by SethBurkart123** [comment]
> > @SethBurkart123 @Crazypersonalph I had spent 1 hour setting flags and settings so It was the most optimal browser for me, it could just be I set the wrong flag or setting. I don't think we should go change things like that when we could be moving BetterSEQTA+ along with new features. Most people just just chrome or edge (yuck). They aren't going to experience the issue I'm having. For the 2 people who are probably using Brave and BetterSEQTA+, we could make a wiki or documentation on the way to fix the issue. We would need the documentation for any big features that get implemented like custom theming and a theme store. Sorry for the essay :)
> 
> Uhh, I believe you seem to underestimate the amount of people who use Brave, let alone ad-blockers, especially school students 💀

I mean there is a chance that we could just show up the error, give them a couple of screenshots on how to fix it. Do one guide for brave browser (as that's probably the only real case that's getting the issues). We can also detect if they are using brave with this line of code:
```
(navigator.brave && await navigator.brave.isBrave() || false)
```
So it's probably possible and/or reasonable to make at least a simple fix for them?

---

Other thing. Easy way out for testing your theory or implementing the change you proposed. I am using for the themes a library called localforage. Which when run from the content script creates an indexedDB in the context of SEQTA. The only problem is it is not accessible from the popup. Now the option of transferring the data over to another script is a bit slow. When I was initially creating it, I tried that option out. But ummm.... It's very slow sending base64 using chromes runtime.sendmessage. And sometimes the files will be relatively large - especially with videos.

**Comment by MEGA-Dawg68** [comment]
> > @SethBurkart123 @Crazypersonalph I had spent 1 hour setting flags and settings so It was the most optimal browser for me, it could just be I set the wrong flag or setting. I don't think we should go change things like that when we could be moving BetterSEQTA+ along with new features. Most people just just chrome or edge (yuck). They aren't going to experience the issue I'm having. For the 2 people who are probably using Brave and BetterSEQTA+, we could make a wiki or documentation on the way to fix the issue. We would need the documentation for any big features that get implemented like custom theming and a theme store. Sorry for the essay :)
> 
> Uhh, I believe you seem to underestimate the amount of people who use Brave, let alone ad-blockers, especially school students 💀

I have tested all the main ad blockers (Ublock, ad block, ad guard) and none of them have stopped BetterSEQTA+, it is just brave. And it must just be my school that is tech illiterate because nobody uses brave here, the only obscure browser used here is firefox and that isn't that obscure. In the telemetry, does it say what web browser is used? I would love to know. But anyway, if you want to fix this then go for it, I don't care overly much. I just like being around an open sourced project on something I care about

**Comment by Crazypersonalph** [comment]
Browser issue out of our control

**Comment by SethBurkart123** [comment]
I just realised I made a bit of a fix for this that just shows people how to disable brave shields but forgot to mention it here :O
