### ISSUE TITLE
CSS Colour issues

### ISSUE THREAD

**Issue by Crazypersonalph** [BetterSEQTA/BetterSEQTA-Plus#91]
On Notices, Courses, Assessments, and Settings, all text is unreadable.

![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/93847055/524a488a-a3d3-4c94-a2bd-3dd8a85ed6a3)

![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/93847055/6192ca88-a258-4640-866a-8d3b93ad164f)

**Comment by SethBurkart123** [comment]
My school doesn't use the notices, so I haven't seen the format or how to use it...

**Comment by Crazypersonalph** [comment]
This bug is still alive and kicking (unfortunately)

**Comment by Crazypersonalph** [comment]
![20240508_21h13m22s_grim](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/93847055/8784088e-b0d9-48e6-b837-29afd663c4ac)

**Comment by SethBurkart123** [comment]
> ![20240508_21h13m22s_grim](https://private-user-images.githubusercontent.com/93847055/328900774-8784088e-b0d9-48e6-b837-29afd663c4ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDQzNjMsIm5iZiI6MTcxNTIwNDA2MywicGF0aCI6Ii85Mzg0NzA1NS8zMjg5MDA3NzQtODc4NDA4OGUtYjBkOS00OGU2LWI4MzctMjlhZmQ2NjNjNGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIxMzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODkyYmVkMmMyZTUxNTQ5YTg5ZjQyZmM3MDQ3NzBiYzM2ODVkNjM1ZGEzNTFmNDllZDc0YzRiMTdiNzA1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B5frSuLSvWZnBJnXiwyKuZqAgJjage-wvbKxv0I-lh4)

Should be just fixed now :) da74655

**Comment by SethBurkart123** [comment]
We'll have to decide what to do about the unreadable text that doesn't have a background...

**Comment by Crazypersonalph** [comment]
Turns out for notices, my old `addIframeCSSToNotices` was removed and replaced with another function called `CheckNoticeTextColour` and this new function broke the Notice colours (my old function fixed the issue).

**Comment by Crazypersonalph** [comment]
Turns out my old function wasn't deleted, but was turned from being pretty simple to being a frankenstein type thing.
Notice colours have been fixed in 8a38b1a

**Comment by ar-cyber** [comment]
It's now fixed. This issue can be closed.

**Comment by Crazypersonalph** [comment]
It's back (again)

**Comment by Crazypersonalph** [comment]
Same issue in Courses as well

**Comment by ar-cyber** [comment]
Can't recreate.

**Comment by Crazypersonalph** [comment]
> Can't recreate.

Maybe Firefox specific issue?

**Comment by SethBurkart123** [comment]
> > Can't recreate.
> 
> Maybe Firefox specific issue?

potentially... the dev and building works a lot better for firefox now, so it will be easier to test and see!

**Comment by Crazypersonalph** [comment]
This can now be put to rest with d1466da on the svelte branch
