### ISSUE TITLE
I always need to reload my page at least once for my full timetable to load

### ISSUE THREAD

**Issue by 135602mevm** [BetterSEQTA/BetterSEQTA-Plus#92]
https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/105038085/c17c1c2f-0ee2-448a-9248-91bf979dd799

I think(?) this is important but the extensions I have are ublock origin (turned off for seqta), a citation generator (mybib) and some random tetris game

Though it really isn't that big of a deal, it's slightly annoying 

Thank you!

**Comment by SethBurkart123** [comment]
Woah! That's weird. We'll definitely have to look into that. _Although I'm not quite sure how to reproduce the bug at the moment._

**Comment by 135602mevm** [comment]
I've reinstalled if a couple times, but I always get the same bug

**Comment by MEGA-Dawg68** [comment]
> I've reinstalled if a couple times, but I always get the same bug

Are you using plain google chrome or a fork of chromium?

**Comment by 135602mevm** [comment]
I just use plain old google chrom I'm pretty sure. It was already installed on my school laptop when I got it, but I'll reinstall it again

**Comment by 135602mevm** [comment]
> > I just use plain old google chrom I'm pretty sure. It was already installed on my school laptop when I got it, but I'll reinstall it again
> > Okay, so I reinstalled google chrome and the extension, but i still get the same thing
> 
> You said something about a tetris extension? if you reinstalled that, go to chrome://extensions and go to details for that extension and check the site access. What does it say?

There is no website that the extension can access in details (the extension: https://chromewebstore.google.com/detail/tetrys/cjobgkekcenldbaenikebmbhffhhffef). 
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/105038085/4abdde24-d986-4b60-8c5c-62d5d9dbb3a1)

**Comment by SethBurkart123** [comment]
I think it's got to do with your schools SEQTA. We'd just have to figure out what inside SEQTA is causing it on your end and fix that. Although it'll be hard to debug for us.

**Comment by ar-cyber** [comment]
Yeah, that's an issue on your end. Are you running a lot of stuff on your computer? Is your school's internet throttled?

**Comment by ar-cyber** [comment]
> Need Bukart to close as no response for 2 months
