### ISSUE TITLE
BUG: Popup doesn't load?

### ISSUE THREAD

**Issue by SethBurkart123** [BetterSEQTA/BetterSEQTA-Plus#94]
I don't know why this is happening. But just take a look at the video.

For some reason when the html is modified it will render fine!? And this only happens in the menu popup!

https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/108050083/ea4de6c8-1030-4436-a85f-98f260847797

**Comment by MEGA-Dawg68** [comment]
Is this only occurring in the latest updates? Can you roll back the latest changes?

**Comment by SethBurkart123** [comment]
> Is this only occurring in the latest updates? Can you roll back the latest changes?

Yes, but no. I figured out it's the colour picker thats giving us issues. But for some reason the problem fixed itself, so I'll post a patch.

**Comment by MEGA-Dawg68** [comment]
So this is all fixed? If it is could we close the issue?
