### ISSUE TITLE
Timetable icons are Inconsistent in colour and size

### ISSUE THREAD

**Issue by thewheelcheese** [BetterSEQTA/BetterSEQTA-Plus#95]
The icons that appear when you click on an element in your timetable are are Inconsistent in colour and size.

![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/161672910/75bc0ebf-2bfe-457b-8dfb-9f587c2e13e2)

**Comment by SethBurkart123** [comment]
Definitely can fix!

**Comment by ar-cyber** [comment]
The colour is fixed, the size is not.

**Comment by ar-cyber** [comment]
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/67220260/1da209eb-da2b-4ead-9cec-f8a7af730b5e)

**Comment by SethBurkart123** [comment]
they are "technically" the same size, but because of how the icons are designed they do look different. I've made a bit of a fix ea0a736a4e02d37af9054a20e29d0698534db668 so hopefully that looks better.
