### ISSUE TITLE
Add and option to use 12 hour time instead of 24 hour time

### ISSUE THREAD

**Issue by thewheelcheese** [BetterSEQTA/BetterSEQTA-Plus#98]
Could you please add an option to view times on your schedule in 12 hour time instead of 24 hour time?
![image](https://github.com/BetterSEQTA/BetterSEQTA-Plus/assets/161672910/77505b9f-3174-4fd3-af39-dd14d14a233e)

**Comment by SethBurkart123** [comment]
Sure, I'll look into adding that!

**Comment by SethBurkart123** [comment]
Available from:

[67a6c8a](https://github.com/BetterSEQTA/BetterSEQTA-Plus/commit/67a6c8ae66d58e77eb473a18915de4faa92bf223)

(Basically in the next update that will now be a feature)
