### ISSUE TITLE
Cant scroll down on welcome page

### ISSUE THREAD

**Issue by DidiDidi129** [BetterSEQTA/BetterSEQTA-Plus#99]
^^^^^^

**Comment by SethBurkart123** [comment]
Hey @DidiDidi129,

I'm not having that problem... I'm not quite sure why it would be doing that for you?


Uploading Screen Recording 2024-03-01 at 3.05.12 pm.mov…

**Comment by SethBurkart123** [comment]
any updates @DidiDidi129?

**Comment by DidiDidi129** [comment]
Sorry for not getting back to you sooner @SethBurkart123. I cant send you a video because my schools info is on the welcome page. I will try to explain here instead we have a section underneath the notices that has links. On normal seqta and betterseqta I can scroll to the links bt I cant on BetterSEQTA+

**Comment by ar-cyber** [comment]
I can't replicate this. Can you try reinstalling the extension?

**Comment by DidiDidi129** [comment]
I think it’s because my school has replaced the welcome screen with their own menu with notices and links. Usually on Seqta and BetterSeqta I can scroll down and see the links but I can’t on BetterSeqta+. I won’t send a video because it has my school branding on it

**Comment by SethBurkart123** [comment]
> I think it’s because my school has replaced the welcome screen with their own menu with notices and links. Usually on Seqta and BetterSeqta I can scroll down and see the links but I can’t on BetterSeqta+. I won’t send a video because it has my school branding on it

Okay, it might take a bit of back and forth to fix because of course we don't have that same styling, I'll apply stuff to try and make the style modifications less likely to break stuff and when it updates you'll just have to let us know when it's fixed, unless of course you want to play around with it yourself.

**Comment by ar-cyber** [comment]
Chances are your school has updated the welcome page, which can cause problems. Possibly clear your cache.

**Comment by ar-cyber** [comment]
We might need to close this as not planned due to inactivity. We'll give you a day to respond, or the issue will be closed.

It's been over a month since the previous comment and we cannot do anything without updates on the process.

**Comment by DidiDidi129** [comment]
> We might need to close this as not planned due to inactivity. We'll give you a day to respond, or the issue will be closed.
> 
> 
> 
> It's been over a month since the previous comment and we cannot do anything without updates on the process.

That's ok, I think the issue is with my school not Better Seqta +
